/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace SavingsTypes {
  export type DepositStruct = {
    depositId: BigNumberish;
    owner: AddressLike;
    planId: BigNumberish;
    principal: BigNumberish;
    startAt: BigNumberish;
    maturityAt: BigNumberish;
    status: BigNumberish;
    accruedInterest: BigNumberish;
  };

  export type DepositStructOutput = [
    depositId: bigint,
    owner: string,
    planId: bigint,
    principal: bigint,
    startAt: bigint,
    maturityAt: bigint,
    status: bigint,
    accruedInterest: bigint
  ] & {
    depositId: bigint;
    owner: string;
    planId: bigint;
    principal: bigint;
    startAt: bigint;
    maturityAt: bigint;
    status: bigint;
    accruedInterest: bigint;
  };

  export type SavingPlanStruct = {
    planId: BigNumberish;
    tenorDays: BigNumberish;
    aprBps: BigNumberish;
    minDeposit: BigNumberish;
    maxDeposit: BigNumberish;
    earlyWithdrawPenaltyBps: BigNumberish;
    enabled: boolean;
    createdAt: BigNumberish;
  };

  export type SavingPlanStructOutput = [
    planId: bigint,
    tenorDays: bigint,
    aprBps: bigint,
    minDeposit: bigint,
    maxDeposit: bigint,
    earlyWithdrawPenaltyBps: bigint,
    enabled: boolean,
    createdAt: bigint
  ] & {
    planId: bigint;
    tenorDays: bigint;
    aprBps: bigint;
    minDeposit: bigint;
    maxDeposit: bigint;
    earlyWithdrawPenaltyBps: bigint;
    enabled: boolean;
    createdAt: bigint;
  };
}

export interface ISavingsPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateInterest"
      | "createPlan"
      | "earlyWithdraw"
      | "feeReceiver"
      | "fundVault"
      | "getDeposit"
      | "getPlan"
      | "getUserDepositCount"
      | "getUserDeposits"
      | "isMatured"
      | "openDeposit"
      | "renew"
      | "setFeeReceiver"
      | "token"
      | "tokenDecimals"
      | "updatePlan"
      | "vaultBalance"
      | "withdrawAtMaturity"
      | "withdrawVault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositOpened"
      | "FeeReceiverSet"
      | "PlanCreated"
      | "PlanUpdated"
      | "Renewed"
      | "VaultFunded"
      | "VaultWithdrawn"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateInterest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPlan",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "earlyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDepositCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDeposits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMatured",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renew",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlan",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAtMaturity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawVault",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateInterest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "earlyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserDepositCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMatured", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "renew", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updatePlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAtMaturity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawVault",
    data: BytesLike
  ): Result;
}

export namespace DepositOpenedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    owner: AddressLike,
    planId: BigNumberish,
    principal: BigNumberish,
    maturityAt: BigNumberish
  ];
  export type OutputTuple = [
    depositId: bigint,
    owner: string,
    planId: bigint,
    principal: bigint,
    maturityAt: bigint
  ];
  export interface OutputObject {
    depositId: bigint;
    owner: string;
    planId: bigint;
    principal: bigint;
    maturityAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeReceiverSetEvent {
  export type InputTuple = [newFeeReceiver: AddressLike];
  export type OutputTuple = [newFeeReceiver: string];
  export interface OutputObject {
    newFeeReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanCreatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    tenorDays: BigNumberish,
    aprBps: BigNumberish,
    minDeposit: BigNumberish,
    maxDeposit: BigNumberish
  ];
  export type OutputTuple = [
    planId: bigint,
    tenorDays: bigint,
    aprBps: bigint,
    minDeposit: bigint,
    maxDeposit: bigint
  ];
  export interface OutputObject {
    planId: bigint;
    tenorDays: bigint;
    aprBps: bigint;
    minDeposit: bigint;
    maxDeposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanUpdatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    aprBps: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [planId: bigint, aprBps: bigint, enabled: boolean];
  export interface OutputObject {
    planId: bigint;
    aprBps: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RenewedEvent {
  export type InputTuple = [
    oldDepositId: BigNumberish,
    newDepositId: BigNumberish,
    newPrincipal: BigNumberish,
    owner: AddressLike
  ];
  export type OutputTuple = [
    oldDepositId: bigint,
    newDepositId: bigint,
    newPrincipal: bigint,
    owner: string
  ];
  export interface OutputObject {
    oldDepositId: bigint;
    newDepositId: bigint;
    newPrincipal: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultWithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    owner: AddressLike,
    principal: BigNumberish,
    interest: BigNumberish,
    isEarly: boolean
  ];
  export type OutputTuple = [
    depositId: bigint,
    owner: string,
    principal: bigint,
    interest: bigint,
    isEarly: boolean
  ];
  export interface OutputObject {
    depositId: bigint;
    owner: string;
    principal: bigint;
    interest: bigint;
    isEarly: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISavingsPool extends BaseContract {
  connect(runner?: ContractRunner | null): ISavingsPool;
  waitForDeployment(): Promise<this>;

  interface: ISavingsPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateInterest: TypedContractMethod<
    [depositId: BigNumberish],
    [bigint],
    "view"
  >;

  createPlan: TypedContractMethod<
    [
      tenorDays: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  earlyWithdraw: TypedContractMethod<
    [depositId: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeReceiver: TypedContractMethod<[], [string], "view">;

  fundVault: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getDeposit: TypedContractMethod<
    [depositId: BigNumberish],
    [SavingsTypes.DepositStructOutput],
    "view"
  >;

  getPlan: TypedContractMethod<
    [planId: BigNumberish],
    [SavingsTypes.SavingPlanStructOutput],
    "view"
  >;

  getUserDepositCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserDeposits: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  isMatured: TypedContractMethod<[depositId: BigNumberish], [boolean], "view">;

  openDeposit: TypedContractMethod<
    [planId: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renew: TypedContractMethod<
    [
      oldDepositId: BigNumberish,
      newPlanId: BigNumberish,
      includeInterest: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  setFeeReceiver: TypedContractMethod<
    [_feeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  tokenDecimals: TypedContractMethod<[], [bigint], "view">;

  updatePlan: TypedContractMethod<
    [planId: BigNumberish, aprBps: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  vaultBalance: TypedContractMethod<[], [bigint], "view">;

  withdrawAtMaturity: TypedContractMethod<
    [depositId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawVault: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateInterest"
  ): TypedContractMethod<[depositId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPlan"
  ): TypedContractMethod<
    [
      tenorDays: BigNumberish,
      aprBps: BigNumberish,
      minDeposit: BigNumberish,
      maxDeposit: BigNumberish,
      earlyWithdrawPenaltyBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "earlyWithdraw"
  ): TypedContractMethod<[depositId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundVault"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [SavingsTypes.DepositStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlan"
  ): TypedContractMethod<
    [planId: BigNumberish],
    [SavingsTypes.SavingPlanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDepositCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserDeposits"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isMatured"
  ): TypedContractMethod<[depositId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "openDeposit"
  ): TypedContractMethod<
    [planId: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renew"
  ): TypedContractMethod<
    [
      oldDepositId: BigNumberish,
      newPlanId: BigNumberish,
      includeInterest: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeReceiver"
  ): TypedContractMethod<[_feeReceiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePlan"
  ): TypedContractMethod<
    [planId: BigNumberish, aprBps: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaultBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawAtMaturity"
  ): TypedContractMethod<[depositId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawVault"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DepositOpened"
  ): TypedContractEvent<
    DepositOpenedEvent.InputTuple,
    DepositOpenedEvent.OutputTuple,
    DepositOpenedEvent.OutputObject
  >;
  getEvent(
    key: "FeeReceiverSet"
  ): TypedContractEvent<
    FeeReceiverSetEvent.InputTuple,
    FeeReceiverSetEvent.OutputTuple,
    FeeReceiverSetEvent.OutputObject
  >;
  getEvent(
    key: "PlanCreated"
  ): TypedContractEvent<
    PlanCreatedEvent.InputTuple,
    PlanCreatedEvent.OutputTuple,
    PlanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PlanUpdated"
  ): TypedContractEvent<
    PlanUpdatedEvent.InputTuple,
    PlanUpdatedEvent.OutputTuple,
    PlanUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Renewed"
  ): TypedContractEvent<
    RenewedEvent.InputTuple,
    RenewedEvent.OutputTuple,
    RenewedEvent.OutputObject
  >;
  getEvent(
    key: "VaultFunded"
  ): TypedContractEvent<
    VaultFundedEvent.InputTuple,
    VaultFundedEvent.OutputTuple,
    VaultFundedEvent.OutputObject
  >;
  getEvent(
    key: "VaultWithdrawn"
  ): TypedContractEvent<
    VaultWithdrawnEvent.InputTuple,
    VaultWithdrawnEvent.OutputTuple,
    VaultWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "DepositOpened(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      DepositOpenedEvent.InputTuple,
      DepositOpenedEvent.OutputTuple,
      DepositOpenedEvent.OutputObject
    >;
    DepositOpened: TypedContractEvent<
      DepositOpenedEvent.InputTuple,
      DepositOpenedEvent.OutputTuple,
      DepositOpenedEvent.OutputObject
    >;

    "FeeReceiverSet(address)": TypedContractEvent<
      FeeReceiverSetEvent.InputTuple,
      FeeReceiverSetEvent.OutputTuple,
      FeeReceiverSetEvent.OutputObject
    >;
    FeeReceiverSet: TypedContractEvent<
      FeeReceiverSetEvent.InputTuple,
      FeeReceiverSetEvent.OutputTuple,
      FeeReceiverSetEvent.OutputObject
    >;

    "PlanCreated(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;
    PlanCreated: TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;

    "PlanUpdated(uint256,uint256,bool)": TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;
    PlanUpdated: TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;

    "Renewed(uint256,uint256,uint256,address)": TypedContractEvent<
      RenewedEvent.InputTuple,
      RenewedEvent.OutputTuple,
      RenewedEvent.OutputObject
    >;
    Renewed: TypedContractEvent<
      RenewedEvent.InputTuple,
      RenewedEvent.OutputTuple,
      RenewedEvent.OutputObject
    >;

    "VaultFunded(address,uint256)": TypedContractEvent<
      VaultFundedEvent.InputTuple,
      VaultFundedEvent.OutputTuple,
      VaultFundedEvent.OutputObject
    >;
    VaultFunded: TypedContractEvent<
      VaultFundedEvent.InputTuple,
      VaultFundedEvent.OutputTuple,
      VaultFundedEvent.OutputObject
    >;

    "VaultWithdrawn(address,uint256)": TypedContractEvent<
      VaultWithdrawnEvent.InputTuple,
      VaultWithdrawnEvent.OutputTuple,
      VaultWithdrawnEvent.OutputObject
    >;
    VaultWithdrawn: TypedContractEvent<
      VaultWithdrawnEvent.InputTuple,
      VaultWithdrawnEvent.OutputTuple,
      VaultWithdrawnEvent.OutputObject
    >;

    "Withdrawn(uint256,address,uint256,uint256,bool)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
